import { Category, Profile, VerificationLevel, Language, ProfileStatus } from './types';

export const UI_TEXT = {
  en: {
    subtitle: "The Archive of Excellence",
    nav_politics: "Politics",
    nav_business: "Business",
    nav_history: "History",
    nav_arts: "Arts & Culture",
    nav_login: "Login",
    hero_title_1: "Discover the History of",
    hero_title_2: "Somali Excellence",
    hero_desc: "The official digital registry for politicians, business leaders, and historical records. Verified. Authoritative. Timeless.",
    search_placeholder: "Search names, companies, or history...",
    search_btn: "Search",
    archive_result: "Archive Search Result",
    generated_by: "Generated by SomaliPin Intelligence",
    no_profiles: "No profiles found in the directory.",
    click_search: "Click \"Search\" to query the Intelligence Archives.",
    featured_dossiers: "Featured Dossiers",
    section_what_we_do: "What we do?",
    service_1_title: "Reputation Building",
    service_1_desc: "We create world-class Digital Dossiers for individuals. We build your profile to have an authoritative presence.",
    service_2_title: "Verification & Security",
    service_2_desc: "The Verified Entity service ensures data authenticity. We provide a verification badge and a unique QR Code.",
    service_3_title: "Legacy Preservation",
    service_3_desc: "We collect, correct, and modernize historical Somali documents (1960–Present), transforming them into digital formats.",
    service_4_title: "Modern Intelligence",
    service_4_desc: "Our platform acts as a dedicated search engine. Your data becomes easily accessible to researchers and investors.",
    back_directory: "Back to Directory",
    contact_office: "Contact Office",
    about: "About",
    timeline: "Historical Timeline",
    key_info: "Key Information",
    label_affiliation: "Affiliation",
    label_role: "Role",
    label_id: "Registry ID",
    verify_title: "Verify This Profile",
    verify_desc: "Scan the official QR code to verify the authenticity of this digital record.",
    tab_archive: "ARCHIVE",
    tab_news: "NEWS",
    tab_influence: "INFLUENCE SCORE",
    upload_doc: "Upload Document",
    click_upload: "Click to upload files",
    upload_hint: "PDF, Images (JPG, PNG), or Awards Certificates",
    no_docs: "No public documents available in this dossier yet.",
    related_reports: "Related Reports & Mentions",
    no_news: "No recent news articles linked to this profile.",
    sentiment_title: "Public Sentiment Analysis",
    sentiment_desc: "Aggregate data based on public perception, verified surveys, and social impact metrics.",
    sentiment_support: "Support",
    sentiment_neutral: "Neutral",
    sentiment_oppose: "Opposition",
    last_updated: "Last updated: Oct 2024",
    footer_desc: "The definitive digital registry for Somali excellence. Archiving the past, validating the present, and inspiring the future.",
    footer_platform: "Platform",
    footer_directory: "Directory",
    footer_verify: "Verification",
    footer_membership: "Membership",
    footer_legal: "Legal",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",
    footer_act: "Data Archive Act",
    footer_contact: "Contact",
    rights: "SomaliPin Digital Archive. All rights reserved.",
    design_integrity: "Designed with Integrity",
    lvl_golden: "Golden Verified",
    lvl_hero: "National Hero",
    lvl_standard: "Verified Entity",
    lvl_unverified: "Unverified",
    // Lifecycle & Status
    lbl_status: "Current Status",
    lbl_born: "Born",
    lbl_died: "Died",
    lbl_est: "Founded",
    lbl_closed: "Closed",
    status_active: "Active",
    status_deceased: "Deceased",
    status_retired: "Retired",
    status_closed: "Closed"
  },
  so: {
    subtitle: "Kaydka Hal-abuurka Soomaaliyeed",
    nav_politics: "Siyaasadda",
    nav_business: "Ganacsiga",
    nav_history: "Taariikhda",
    nav_arts: "Farshaxanka & Dhaqanka",
    nav_login: "Galid",
    hero_title_1: "Sahamo Taariikhda",
    hero_title_2: "Hal-doorka Soomaaliyeed",
    hero_desc: "Diiwaanka rasmiga ah ee hoggaamiyeyaasha siyaasadda, ganacsatada, iyo kaydka taariikhda. La hubiyay. Lagu kalsoonaan karo. Waara.",
    search_placeholder: "Baar magacyada, shirkadaha, ama taariikhda...",
    search_btn: "Baar",
    archive_result: "Natiijada Baarista Kaydka",
    generated_by: "Waxaa soo saaray SomaliPin Intelligence",
    no_profiles: "Lagama helin diiwaanka.",
    click_search: "Guji \"Baar\" si aad u weydiiso Kaydka Sirdoonka.",
    featured_dossiers: "Diiwaanada Ugu Muhiimsan",
    section_what_we_do: "Maxaan qabanaa?",
    service_1_title: "Dhisidda Sumcadda",
    service_1_desc: "Waxaan shaqsiyaadka u samaynaa \"Digital Dossiers\" heer caalami ah. Waxaanu dhisnaa profile-kaaga si uu u yeesho muuqaal mas'uuliyadeed.",
    service_2_title: "Hubinta & Sugidda",
    service_2_desc: "Adeegga \"Verified Entity\" wuxuu hubinayaa in xogtaadu tahay mid rasmi ah. Waxaanu ku siinaynaa calaamadda hubinta iyo QR Code u gaar ah.",
    service_3_title: "Dib-u-habaynta Dhaxalka",
    service_3_desc: "Waxaanu ururinaa, saxnaa, oo aanu casriyeynaa dokumentiyada taariikhiga ah ee Soomaaliya (1960–Maanta).",
    service_4_title: "Xog-Raadinta Casriga ah",
    service_4_desc: "Platform-keenu wuxuu u shaqeeyaa sidii matoor xog-raadineed (Search Engine) oo kale. Xogtaada waxaa si fudud u heli kara cilmi-baarayaasha.",
    back_directory: "Ku laabo Diiwaanka",
    contact_office: "La Xiriir Xafiiska",
    about: "Faahfaahin",
    timeline: "Dhacdooyinka Taariikhiga ah",
    key_info: "Xogta Muhiimka ah",
    label_affiliation: "Heerka",
    label_role: "Doorka",
    label_id: "Lambarka Aqoonsiga",
    verify_title: "Xaqiiji Profile-kan",
    verify_desc: "Sawir QR code-ka rasmiga ah si aad u xaqiijiso saxnimada diiwaankan dhijitaalka ah.",
    tab_archive: "KAYDKA",
    tab_news: "WARARKA",
    tab_influence: "HEERKA SAAMAYNTA",
    upload_doc: "Soo Geli Document",
    click_upload: "Guji si aad u soo geliso",
    upload_hint: "PDF, Sawirro (JPG, PNG), ama Shahaadooyin",
    no_docs: "Weli laguma darin dokumentiyo dadweyne diiwaankan.",
    related_reports: "Warbixinada La Xiriira",
    no_news: "Ma jiraan warar dhowaan la xiriira profile-kan.",
    sentiment_title: "Falanqaynta Ra'yiga Dadweynaha",
    sentiment_desc: "Xog la isku geeyay oo ku salaysan aragtida dadweynaha, sahanno la hubiyay, iyo cabbirrada saamaynta bulshada.",
    sentiment_support: "Taageero",
    sentiment_neutral: "Dhexdhexaad",
    sentiment_oppose: "Diidmo",
    last_updated: "Cusbooneysiinta u dambaysay: Okt 2024",
    footer_desc: "Diiwaanka dhijitaalka ah ee rasmiga ah ee heerka sare ee Soomaaliya. Kaydinta tagtada, xaqiijinta timaadada.",
    footer_platform: "Madal",
    footer_directory: "Diiwaanka",
    footer_verify: "Hubinta",
    footer_membership: "Xubinimada",
    footer_legal: "Sharciga",
    footer_privacy: "Siyaasadda Khaaska ah",
    footer_terms: "Shuruudaha Adeegga",
    footer_act: "Xeerka Kaydka Xogta",
    footer_contact: "Xiriirka",
    rights: "SomaliPin Digital Archive. Xuquuqda oo dhan way dhowran yihiin.",
    design_integrity: "Lagu dhisay Hufnaan",
    lvl_golden: "Heerka Sare",
    lvl_hero: "Halyey Qaran",
    lvl_standard: "Rasmi",
    lvl_unverified: "Lama Xaqiijin",
    // Lifecycle & Status
    lbl_status: "Xaaladda",
    lbl_born: "Dhalashada",
    lbl_died: "Dhimashada",
    lbl_est: "La Aasaasay",
    lbl_closed: "Xirmay",
    status_active: "Shaqeeya",
    status_deceased: "Geeriyooday",
    status_retired: "Hoolgab",
    status_closed: "Xirmay"
  },
  ar: {
    subtitle: "أرشيف التميز الصومالي",
    nav_politics: "السياسة",
    nav_business: "الأعمال",
    nav_history: "التاريخ",
    nav_arts: "الفنون والثقافة",
    nav_login: "دخول",
    hero_title_1: "اكتشف تاريخ",
    hero_title_2: "التميز الصومالي",
    hero_desc: "السجل الرقمي الرسمي للسياسيين وقادة الأعمال والسجلات التاريخية. موثق. معتمد. خالد.",
    search_placeholder: "ابحث عن الأسماء، الشركات، أو التاريخ...",
    search_btn: "بحث",
    archive_result: "نتيجة بحث الأرشيف",
    generated_by: "تم الإنشاء بواسطة ذكاء الصومال بن",
    no_profiles: "لم يتم العثور على ملفات تعريف في الدليل.",
    click_search: "انقر فوق \"بحث\" للاستعلام في أرشيف الاستخبارات.",
    featured_dossiers: "ملفات مميزة",
    section_what_we_do: "ماذا نقدم؟",
    service_1_title: "بناء السمعة",
    service_1_desc: "نقوم بإنشاء ملفات رقمية عالمية المستوى للأفراد. نبني ملفك الشخصي ليكون له حضور رسمي ومسؤول.",
    service_2_title: "التحقق والأمان",
    service_2_desc: "تضمن خدمة \"الكيان الموثق\" صحة البيانات. نوفر شارة التحقق ورمز استجابة سريعة (QR) فريد.",
    service_3_title: "حفظ الإرث",
    service_3_desc: "نقوم بجمع وتصحيح وتحديث الوثائق التاريخية الصومالية (1960-الآن) وتحويلها إلى تنسيقات رقمية.",
    service_4_title: "الاستخبارات الحديثة",
    service_4_desc: "تعمل منصتنا كمحرك بحث مخصص. تصبح بياناتك سهلة الوصول للباحثين والمستثمرين.",
    back_directory: "العودة إلى الدليل",
    contact_office: "اتصل بالمكتب",
    about: "حول",
    timeline: "الجدول الزمني التاريخي",
    key_info: "معلومات أساسية",
    label_affiliation: "الانتماء",
    label_role: "الدور",
    label_id: "معرف السجل",
    verify_title: "تحقق من هذا الملف",
    verify_desc: "امسح رمز الاستجابة السريعة الرسمي للتحقق من صحة هذا السجل الرقمي.",
    tab_archive: "الأرشيف",
    tab_news: "الأخبار",
    tab_influence: "نقاط التأثير",
    upload_doc: "تحميل مستند",
    click_upload: "انقر للتحميل",
    upload_hint: "PDF، صور (JPG، PNG)، أو شهادات",
    no_docs: "لا توجد مستندات عامة متاحة في هذا الملف حتى الآن.",
    related_reports: "التقارير والإشارات ذات الصلة",
    no_news: "لا توجد مقالات إخبارية حديثة مرتبطة بهذا الملف.",
    sentiment_title: "تحليل المشاعر العامة",
    sentiment_desc: "بيانات مجمعة بناءً على التصور العام والاستطلاعات المؤكدة ومقاييس التأثير الاجتماعي.",
    sentiment_support: "دعم",
    sentiment_neutral: "محايد",
    sentiment_oppose: "معارضة",
    last_updated: "آخر تحديث: أكتوبر 2024",
    footer_desc: "السجل الرقمي الرسمي للتميز الصومالي. أرشفة الماضي، والتحقق من الحاضر، وإلهام المستقبل.",
    footer_platform: "المنصة",
    footer_directory: "الدليل",
    footer_verify: "التحقق",
    footer_membership: "العضوية",
    footer_legal: "قانوني",
    footer_privacy: "سياسة الخصوصية",
    footer_terms: "شروط الخدمة",
    footer_act: "قانون أرشيف البيانات",
    footer_contact: "اتصل بنا",
    rights: "أرشيف الصومال بن الرقمي. جميع الحقوق محفوظة.",
    design_integrity: "صمم بنزاهة",
    lvl_golden: "موثق ذهبي",
    lvl_hero: "بطل وطني",
    lvl_standard: "كيان رسمي",
    lvl_unverified: "غير موثق",
    // Lifecycle & Status
    lbl_status: "الحالة",
    lbl_born: "الميلاد",
    lbl_died: "الوفاة",
    lbl_est: "تأسست",
    lbl_closed: "مغلق",
    status_active: "نشط",
    status_deceased: "متوفي",
    status_retired: "متقاعد",
    status_closed: "مغلق"
  }
};

const CATEGORY_MAP: Record<Category, keyof typeof UI_TEXT['en']> = {
  [Category.POLITICS]: 'nav_politics',
  [Category.BUSINESS]: 'nav_business',
  [Category.HISTORY]: 'nav_history',
  [Category.ARTS]: 'nav_arts'
};

const RAW_DATA = [
  {
    id: '1',
    category: Category.HISTORY,
    verified: true,
    verificationLevel: VerificationLevel.GOLDEN,
    imageUrl: 'https://picsum.photos/200/200?grayscale',
    influence: { support: 95, neutral: 3, opposition: 2 },
    isOrganization: false,
    status: 'DECEASED' as ProfileStatus,
    dateStart: '1908',
    dateEnd: '2007',
    content: {
      en: {
        name: 'Aden Adde',
        title: 'First President of Somalia',
        location: 'Mogadishu, Somalia',
        shortBio: 'Aden Abdullah Osman Daar was a Somali politician who served as the first President of the Somali Republic from 1960 to 1967.',
        fullBio: 'Aden Abdullah Osman Daar (Aden Adde) is celebrated as the father of Somali democracy. Born in Beledweyne, he joined the Somali Youth League (SYL) in 1944 and rose through the ranks to become a pivotal figure in the independence movement. His presidency is remembered for its peaceful transfer of power, a historic precedent in post-colonial Africa.',
        timeline: [
            { year: '1908', title: 'Birth', description: 'Born in Beledweyne, Hiiraan region.' },
            { year: '1944', title: 'SYL Member', description: 'Joined the Somali Youth League.' },
            { year: '1960', title: 'Presidency', description: 'Elected as the first President of the Somali Republic.' },
            { year: '1967', title: 'Peaceful Transfer', description: 'First African leader to peacefully hand over power to a democratically elected successor.' }
        ],
        archives: [
            { id: 'a1', type: 'PDF' as const, title: 'Official Independence Speech 1960', date: 'Jul 1, 1960', size: '2.4 MB' },
            { id: 'a2', type: 'IMAGE' as const, title: 'Inauguration Ceremony Photo', date: 'Jul 1, 1960', size: '4.1 MB' },
            { id: 'a3', type: 'AWARD' as const, title: 'Order of the Star of Somalia', date: '1965', size: 'High Res' }
        ],
        news: [
            { id: 'n1', title: 'The Legacy of Aden Adde: A Model for Democracy', source: 'Historical Review', date: 'June 2023', summary: 'An in-depth look at how the first president established democratic norms in the horn of Africa.' },
            { id: 'n2', title: 'Airport Renaming Ceremony Anniversary', source: 'Mogadishu Times', date: 'Jan 2024', summary: 'Celebrations mark the anniversary of renaming Mogadishu International Airport in his honor.' }
        ]
      },
      so: {
        name: 'Aadan Cadde',
        title: 'Madaxweynihii Ugu Horeeyay ee Soomaaliya',
        location: 'Muqdisho, Soomaaliya',
        shortBio: 'Aadan Cabdulle Cusmaan Daar wuxuu ahaa siyaasi Soomaaliyeed oo noqday Madaxweynihii ugu horeeyay ee Jamhuuriyadda Soomaaliya intii u dhaxaysay 1960 ilaa 1967.',
        fullBio: 'Aadan Cabdulle Cusmaan Daar (Aadan Cadde) waxaa lagu tiriyaa aabaha dimuqraadiyadda Soomaaliya. Wuxuu ku dhashay Beledweyne, wuxuuna ku biiray Ururkii Dhalinyarada Soomaaliyeed (SYL) 1944. Madaxweynanimadiisii waxaa lagu xusuustaa xil-wareejintii nabadeed, taasoo ahayd dhacdo taariikhi ah Afrika.',
        timeline: [
            { year: '1908', title: 'Dhalasho', description: 'Wuxuu ku dhashay Beledweyne, gobolka Hiiraan.' },
            { year: '1944', title: 'Xubin SYL', description: 'Wuxuu ku biiray Ururkii Dhalinyarada Soomaaliyeed.' },
            { year: '1960', title: 'Madaxweynenimo', description: 'Waxaa loo doortay Madaxweynihii ugu horeeyay ee Jamhuuriyadda Soomaaliya.' },
            { year: '1967', title: 'Xil Wareejin', description: 'Hoggaamiyihii ugu horeeyay ee Afrika ee si nabad ah xilka u wareejiya.' }
        ],
        archives: [
            { id: 'a1', type: 'PDF' as const, title: 'Khudbaddii Xorriyadda 1960', date: 'Luulyo 1, 1960', size: '2.4 MB' },
            { id: 'a2', type: 'IMAGE' as const, title: 'Sawirka Xafladda Caleema Saarka', date: 'Luulyo 1, 1960', size: '4.1 MB' },
            { id: 'a3', type: 'AWARD' as const, title: 'Abaalmarinta Xiddigta Soomaaliya', date: '1965', size: 'Sare' }
        ],
        news: [
            { id: 'n1', title: 'Dhaxalkii Aadan Cadde: Tusaale u ah Dimuqraadiyadda', source: 'Dib u eegista Taariikhda', date: 'Juun 2023', summary: 'Eegid qoto dheer sida madaxweynihii ugu horeeyay u hirgeliyay nidaamka dimuqraadiyadda Geeska Afrika.' },
            { id: 'n2', title: 'Xuska Magac-bixinta Garoonka Diyaaradaha', source: 'Wargeyska Muqdisho', date: 'Jan 2024', summary: 'Dabaaldegyo lagu xusayo sannad-guurada magac-bixinta Garoonka Caalamiga ah ee Aadan Cadde.' }
        ]
      },
      ar: {
        name: 'آدم عدي',
        title: 'أول رئيس للصومال',
        location: 'مقديشو، الصومال',
        shortBio: 'آدم عبد الله عثمان دار كان سياسياً صومالياً شغل منصب أول رئيس لجمهورية الصومال من 1960 إلى 1967.',
        fullBio: 'يحتفل بآدم عبد الله عثمان دار (آدم عدي) كأب للديمقراطية الصومالية. ولد في بلدوين، وانضم إلى رابطة الشباب الصومالي (SYL) في عام 1944. وتُذكر رئاسته بانتقال السلطة السلمي، وهي سابقة تاريخية في أفريقيا ما بعد الاستعمار.',
        timeline: [
            { year: '1908', title: 'الميلاد', description: 'ولد في بلدوين، منطقة هيران.' },
            { year: '1944', title: 'عضو SYL', description: 'انضم إلى رابطة الشباب الصومالي.' },
            { year: '1960', title: 'الرئاسة', description: 'انتخب كأول رئيس لجمهورية الصومال.' },
            { year: '1967', title: 'النقل السلمي', description: 'أول زعيم أفريقي يسلم السلطة سلمياً لخليفة منتخب ديمقراطياً.' }
        ],
        archives: [
            { id: 'a1', type: 'PDF' as const, title: 'خطاب الاستقلال الرسمي 1960', date: '1 يوليو 1960', size: '2.4 MB' },
            { id: 'a2', type: 'IMAGE' as const, title: 'صورة حفل التنصيب', date: '1 يوليو 1960', size: '4.1 MB' },
            { id: 'a3', type: 'AWARD' as const, title: 'وسام نجمة الصومال', date: '1965', size: 'دقة عالية' }
        ],
        news: [
            { id: 'n1', title: 'إرث آدم عدي: نموذج للديمقراطية', source: 'المراجعة التاريخية', date: 'يونيو 2023', summary: 'نظرة متعمقة حول كيفية ترسيخ الرئيس الأول للمعايير الديمقراطية في القرن الأفريقي.' },
            { id: 'n2', title: 'ذكرى إعادة تسمية المطار', source: 'أوقات مقديشو', date: 'يناير 2024', summary: 'احتفالات بمناسبة ذكرى إعادة تسمية مطار مقديشو الدولي تكريماً له.' }
        ]
      }
    }
  },
  {
    id: 'hero-1',
    category: Category.HISTORY,
    verified: true,
    verificationLevel: VerificationLevel.HERO,
    imageUrl: 'https://picsum.photos/205/205?grayscale',
    influence: { support: 99, neutral: 1, opposition: 0 },
    isOrganization: false,
    status: 'DECEASED' as ProfileStatus,
    dateStart: 'Unknown',
    dateEnd: '2022',
    content: {
      en: {
        name: 'Gen. Farhan Qaroole',
        title: 'Commander of Mogadishu Police',
        location: 'Mogadishu / Bal\'ad',
        shortBio: 'General Farhan Mohamoud Adan (Qaroole) was a legendary commander known for leading from the front lines in the fight for Somalia\'s security.',
        fullBio: 'General Farhan Mohamoud Adan, popularly known as "Qaroole", was a symbol of bravery and resilience. As the Police Commander of Mogadishu, he personally led operations against terror groups, prioritizing the safety of citizens above his own life. He was martyred in an explosion in 2022 while on duty.',
        timeline: [
            { year: 'Early Career', title: 'Service', description: 'Joined the security forces dedicating his life to stabilizing the capital.' },
            { year: '2021', title: 'Police Commander', description: 'Appointed as the Mogadishu Police Commander.' },
            { year: '2022', title: 'Martyrdom', description: 'Tragically killed in a roadside explosion near Bal\'ad while leading a security operation.' }
        ],
        archives: [
            { id: 'h1', type: 'AWARD' as const, title: 'Medal of Honor (Posthumous)', date: '2022', size: 'Image' },
            { id: 'h2', type: 'IMAGE' as const, title: 'Field Operation Archive', date: '2021', size: '3.5 MB' }
        ],
        news: [
            { id: 'hn1', title: 'Nation Mourns General Farhan Qaroole', source: 'State Media', date: 'Sept 2022', summary: 'Thousands gather to pay respects to the fallen commander who dedicated his life to peace.' }
        ]
      },
      so: {
        name: 'Gen. Farxaan Qaroole',
        title: 'Taliyihii Booliska Gobolka Banaadir',
        location: 'Muqdisho / Balcad',
        shortBio: 'Jeneraal Farxaan Maxamuud Aadan (Qaroole) wuxuu ahaa taliye halyeey ah oo caan ku ahaa inuu hogaamiyo dagaalka jiidda hore.',
        fullBio: 'Jeneraal Farxaan Maxamuud Aadan, oo loo yaqaan "Qaroole", wuxuu astaan u ahaa geesinimada. Taliyihii Booliska Muqdisho ahaan, wuxuu shakhsiyan hoggaamiyay hawlgallo ka dhan ah argagixisada. Waxaa lagu dilay qarax 2022 isagoo gudanaaya waajibkiisa qaran.',
        timeline: [
            { year: 'Bilowgii', title: 'Adeegga', description: 'Wuxuu ku biiray ciidamada amniga isagoo naftiisa u huray xasilinta caasimadda.' },
            { year: '2021', title: 'Taliyaha Booliska', description: 'Waxaa loo magacaabay Taliyaha Booliska Muqdisho.' },
            { year: '2022', title: 'Shahiid', description: 'Wuxuu si murugo leh ugu dhintay qarax miino meel u dhow Balcad.' }
        ],
        archives: [
            { id: 'h1', type: 'AWARD' as const, title: 'Biladda Sharaf (Geerida Kadib)', date: '2022', size: 'Sawir' },
            { id: 'h2', type: 'IMAGE' as const, title: 'Kaydka Hawlgalka', date: '2021', size: '3.5 MB' }
        ],
        news: [
            { id: 'hn1', title: 'Qaranka oo u Baroordiiqaya Jeneraal Farxaan Qaroole', source: 'Warbaahinta Qaranka', date: 'Seb 2022', summary: 'Kumanaan dadweyne ah ayaa isugu soo baxay si ay u xushmeeyaan taliyihii geeriyooday ee naftiisa u huray nabadda.' }
        ]
      },
      ar: {
        name: 'الجنرال فرحان قارولي',
        title: 'قائد شرطة مقديشو',
        location: 'مقديشو / بلد',
        shortBio: 'كان اللواء فرحان محمود عدن (قارولي) قائدًا أسطوريًا معروفًا بالقيادة من الخطوط الأمامية في القتال من أجل أمن الصومال.',
        fullBio: 'كان اللواء فرحان محمود عدن، المعروف شعبياً باسم "قارولي"، رمزاً للشجاعة والصمود. وبصفته قائد شرطة مقديشو، قاد شخصياً عمليات ضد الجماعات الإرهابية. استشهد في انفجار عام 2022 أثناء تأديته لواجبه.',
        timeline: [
            { year: 'بداية المسيرة', title: 'الخدمة', description: 'انضم إلى قوات الأمن وكرس حياته لاستقرار العاصمة.' },
            { year: '2021', title: 'قائد الشرطة', description: 'عين قائدا لشرطة مقديشو.' },
            { year: '2022', title: 'الشهادة', description: 'استشهد بشكل مأساوي في انفجار عبوة ناسفة بالقرب من بلد.' }
        ],
        archives: [
            { id: 'h1', type: 'AWARD' as const, title: 'وسام الشرف (بعد الوفاة)', date: '2022', size: 'صورة' },
            { id: 'h2', type: 'IMAGE' as const, title: 'أرشيف العمليات الميدانية', date: '2021', size: '3.5 MB' }
        ],
        news: [
            { id: 'hn1', title: 'الأمة تنعي الجنرال فرحان قارولي', source: 'إعلام الدولة', date: 'سبتمبر 2022', summary: 'الآلاف يتجمعون لتقديم العزاء للقائد الشهيد الذي كرس حياته للسلام.' }
        ]
      }
    }
  },
  {
    id: '2',
    category: Category.BUSINESS,
    verified: true,
    verificationLevel: VerificationLevel.GOLDEN,
    imageUrl: 'https://picsum.photos/201/201?grayscale',
    influence: { support: 92, neutral: 6, opposition: 2 },
    isOrganization: true,
    status: 'ACTIVE' as ProfileStatus,
    dateStart: '1970',
    content: {
      en: {
        name: 'Dahabshiil Group',
        title: 'Global Money Transfer & Energy',
        location: 'Hargeisa / Dubai / London',
        shortBio: 'The largest African money transfer operator, Dahabshiil has become a cornerstone of the Somali economy and global remittances.',
        fullBio: 'Founded by Mohamed Said Duale in 1970, Dahabshiil began as a small trading enterprise. Following the civil war, it pioneered a trust-based money transfer system that kept the Somali economy afloat. Today, it is a multi-national conglomerate.',
        timeline: [
            { year: '1970', title: 'Founded', description: 'Established as a general trading business.' },
            { year: '1990s', title: 'Remittance Expansion', description: 'Expanded services to serve the Somali diaspora during the civil war.' },
            { year: '2009', title: 'Banking License', description: 'Launched Dahabshiil Bank International.' },
            { year: 'Present', title: 'Global Reach', description: 'Operating in over 126 countries worldwide.' }
        ],
        archives: [
            { id: 'b1', type: 'PDF' as const, title: 'Annual Sustainability Report 2023', date: 'Dec 2023', size: '5.2 MB' },
            { id: 'b2', type: 'AWARD' as const, title: 'Global Excellence in Finance', date: '2022', size: 'N/A' }
        ],
        news: [
            { id: 'bn1', title: 'Dahabshiil Launches New Micro-finance Initiative', source: 'Financial Post', date: 'Mar 2024', summary: 'The group announces 5 million USD fund to support small businesses in the region.' }
        ]
      },
      so: {
        name: 'Shirkadda Dahabshiil',
        title: 'Xawaaladaha & Tamarta Caalamiga ah',
        location: 'Hargeysa / Dubai / London',
        shortBio: 'Dahabshiil oo ah shirkadda ugu weyn ee xawaaladaha Afrika, waxay noqotay udub dhexaadka dhaqaalaha Soomaaliya.',
        fullBio: 'Waxaa aasaasay Maxamed Siciid Ducaale 1970, waxayna ku bilaabatay ganacsi yar. Dagaalkii sokeeye ka dib, waxay hormuud ka noqotay nidaamka xawaaladaha oo dhaqaalaha Soomaaliya badbaadiyay. Maanta waa shirkad caalami ah.',
        timeline: [
            { year: '1970', title: 'Aasaaskii', description: 'Waxaa loo aasaasay ganacsi guud.' },
            { year: '1990s', title: 'Fidinta Xawaaladda', description: 'Waxay ballaarisay adeegyada qurba-joogta intii lagu jiray dagaalkii sokeeye.' },
            { year: '2009', title: 'Liisanka Bangiga', description: 'Waxay daah-furtay Bangiga Caalamiga ah ee Dahabshiil.' },
            { year: 'Hadda', title: 'Gaarista Caalamka', description: 'Waxay ka hawlgashaa in ka badan 126 waddan.' }
        ],
        archives: [
            { id: 'b1', type: 'PDF' as const, title: 'Warbixinta Joogtaynta Sannadlaha 2023', date: 'Dis 2023', size: '5.2 MB' },
            { id: 'b2', type: 'AWARD' as const, title: 'Abaalmarinta Caalamiga ah ee Maaliyadda', date: '2022', size: 'N/A' }
        ],
        news: [
            { id: 'bn1', title: 'Dahabshiil oo Daahfurtay Hindise Cusub', source: 'Wargeyska Ganacsiga', date: 'Mar 2024', summary: 'Kooxda ayaa ku dhawaaqday sanduuq lacageed oo dhan 5 milyan oo doolar oo lagu taageerayo ganacsiyada yaryar.' }
        ]
      },
      ar: {
        name: 'مجموعة دهب شيل',
        title: 'تحويل الأموال والطاقة العالمية',
        location: 'هرجيسا / دبي / لندن',
        shortBio: 'أصبحت دهب شيل، أكبر مشغل لتحويل الأموال في أفريقيا، حجر الزاوية في الاقتصاد الصومالي والتحويلات المالية العالمية.',
        fullBio: 'تأسست دهب شيل على يد محمد سعيد دعاله في عام 1970 كشركة تجارية صغيرة. بعد الحرب الأهلية، ابتكرت نظام تحويل أموال قائم على الثقة أبقى الاقتصاد الصومالي واقفاً على قدميه. اليوم، هي تكتل متعدد الجنسيات.',
        timeline: [
            { year: '1970', title: 'التأسيس', description: 'تأسست كشركة تجارية عامة.' },
            { year: '1990s', title: 'توسع التحويلات', description: 'توسيع الخدمات لخدمة الشتات الصومالي خلال الحرب الأهلية.' },
            { year: '2009', title: 'ترخيص بنكي', description: 'إطلاق بنك دهب شيل الدولي.' },
            { year: 'الحاضر', title: 'الانتشار العالمي', description: 'تعمل في أكثر من 126 دولة حول العالم.' }
        ],
        archives: [
            { id: 'b1', type: 'PDF' as const, title: 'تقرير الاستدامة السنوي 2023', date: 'ديسمبر 2023', size: '5.2 MB' },
            { id: 'b2', type: 'AWARD' as const, title: 'التميز العالمي في التمويل', date: '2022', size: 'N/A' }
        ],
        news: [
            { id: 'bn1', title: 'دهب شيل تطلق مبادرة جديدة للتمويل الأصغر', source: 'المنشور المالي', date: 'مارس 2024', summary: 'تعلن المجموعة عن صندوق بقيمة 5 ملايين دولار لدعم الشركات الصغيرة في المنطقة.' }
        ]
      }
    }
  },
  {
    id: '3',
    category: Category.HISTORY,
    verified: true,
    verificationLevel: VerificationLevel.HERO,
    imageUrl: 'https://picsum.photos/202/202?grayscale',
    influence: { support: 98, neutral: 2, opposition: 0 },
    isOrganization: false,
    status: 'DECEASED' as ProfileStatus,
    dateStart: '1947',
    dateEnd: '2020',
    content: {
      en: {
        name: 'Dr. Hawa Abdi',
        title: 'Human Rights Activist & Physician',
        location: 'Mogadishu',
        shortBio: 'A Somali human rights activist and physician known as the "Mother of Somalia" for her non-sectarian humanitarian work.',
        fullBio: 'Dr. Hawa Abdi Diblaawe was a beacon of hope. She established a clinic in 1983 that eventually grew into a massive camp housing 90,000 displaced people. She fiercely defended her camp against militias, maintaining it as a neutral, peaceful ground.',
        timeline: [
            { year: '1947', title: 'Birth', description: 'Born in Mogadishu.' },
            { year: '1971', title: 'Medical Degree', description: 'Became one of Somalia\'s first female gynecologists.' },
            { year: '1983', title: 'Clinic Founded', description: 'Opened the Rural Health Development Organisation (RHDO).' },
            { year: '2012', title: 'Nobel Nomination', description: 'Nominated for the Nobel Peace Prize for her humanitarian efforts.' }
        ],
        archives: [],
        news: []
      },
      so: {
        name: 'Dr. Xaawo Cabdi',
        title: 'Dhaqtarrad & U Doodaha Xuquuqda Aadanaha',
        location: 'Muqdisho',
        shortBio: 'Dhaqtarrad iyo u dhaqdhaqaaqe xuquuqda aadanaha oo loo yaqaan "Hooyada Soomaaliya" shaqadeeda samafal awgeed.',
        fullBio: 'Dr. Xaawo Cabdi Dhiblaawe waxay ahayd ilays rajo. Waxay aasaastay rug caafimaad 1983-dii oo markii dambe noqotay xero weyn oo ay ku nool yihiin 90,000 oo barakacayaal ah. Waxay si adag u difaacday xeradeeda, iyadoo ka dhigtay goob nabdoon.',
        timeline: [
            { year: '1947', title: 'Dhalasho', description: 'Waxay ku dhalatay Muqdisho.' },
            { year: '1971', title: 'Shahaadada Caafimaadka', description: 'Waxay noqotay mid ka mid ah dhaqaatiirta haweenka ee ugu horeeyay Soomaaliya.' },
            { year: '1983', title: 'Aasaaska Rugta', description: 'Waxay furtay Ururka Horumarinta Caafimaadka Miyiga (RHDO).' },
            { year: '2012', title: 'Magacaabista Nobel', description: 'Waxaa loo magacaabay Abaalmarinta Nabadda ee Nobel.' }
        ],
        archives: [],
        news: []
      },
      ar: {
        name: 'د. حواء عبدي',
        title: 'ناشطة حقوق الإنسان وطبيبة',
        location: 'مقديشو',
        shortBio: 'ناشطة حقوقية وطبيبة صومالية تعرف بلقب "أم الصومال" لعملها الإنساني غير الطائفي.',
        fullBio: 'كانت الدكتورة حواء عبدي ديبلاوي منارة للأمل. أنشأت عيادة في عام 1983 نمت لتصبح مخيماً ضخماً يضم 90,000 نازح. دافعت بشراسة عن مخيمها ضد الميليشيات، وحافظت عليه كأرض محايدة ومسالمة.',
        timeline: [
            { year: '1947', title: 'الميلاد', description: 'ولدت في مقديشو.' },
            { year: '1971', title: 'الشهادة الطبية', description: 'أصبحت واحدة من أوائل طبيبات النساء في الصومال.' },
            { year: '1983', title: 'تأسيس العيادة', description: 'افتتحت منظمة تنمية الصحة الريفية (RHDO).' },
            { year: '2012', title: 'ترشيح نوبل', description: 'رشحت لجائزة نوبل للسلام لجهودها الإنسانية.' }
        ],
        archives: [],
        news: []
      }
    }
  },
  {
    id: '4',
    category: Category.BUSINESS,
    verified: true,
    verificationLevel: VerificationLevel.GOLDEN,
    imageUrl: 'https://picsum.photos/203/203?grayscale',
    influence: { support: 70, neutral: 20, opposition: 10 },
    isOrganization: true,
    status: 'ACTIVE' as ProfileStatus,
    dateStart: '2002',
    content: {
      en: {
        name: 'Hormuud Telecom',
        title: 'Telecommunications Giant',
        location: 'Mogadishu, Somalia',
        shortBio: 'Leading telecommunications provider in Somalia, driving the mobile money revolution with EVC Plus.',
        fullBio: 'Hormuud Telecom Somalia Inc. was established in 2002. It quickly became the market leader, introducing GSM mobile services, fixed lines, and arguably its most impactful product, EVC Plus, which transformed Somalia into a largely cashless society.',
        timeline: [
            { year: '2002', title: 'Establishment', description: 'Founded by a group of shareholders in Mogadishu.' },
            { year: '2011', title: 'EVC Plus', description: 'Launched the mobile money service EVC Plus.' },
            { year: '2013', title: '4G LTE', description: 'First to introduce 4G services in the region.' }
        ],
        archives: [],
        news: []
      },
      so: {
        name: 'Shirkadda Hormuud',
        title: 'Hormuudka Isgaarsiinta',
        location: 'Muqdisho, Soomaaliya',
        shortBio: 'Shirkadda isgaarsiinta ee ugu weyn Soomaaliya, horseedna u ah adeegga lacagaha mobile-ka ee EVC Plus.',
        fullBio: 'Hormuud Telecom Somalia Inc. waxaa la aasaasay 2002. Waxay si dhakhso ah u noqotay hoggaamiyaha suuqa, iyadoo soo bandhigtay adeegyada GSM, iyo EVC Plus oo Soomaaliya ka dhigay bulsho aan lacag caddaan ah isticmaalin.',
        timeline: [
            { year: '2002', title: 'Aasaaskii', description: 'Waxaa aasaasay koox saamilay ah oo ku sugan Muqdisho.' },
            { year: '2011', title: 'EVC Plus', description: 'Daah-furka adeegga lacagaha mobile-ka ee EVC Plus.' },
            { year: '2013', title: '4G LTE', description: 'Tii ugu horreysay ee soo bandhigta adeegyada 4G ee gobolka.' }
        ],
        archives: [],
        news: []
      },
      ar: {
        name: 'هرمود للاتصالات',
        title: 'عملاق الاتصالات',
        location: 'مقديشو، الصومال',
        shortBio: 'مزود الاتصالات الرائد في الصومال، تقود ثورة الأموال عبر الهاتف المحمول مع خدمة EVC Plus.',
        fullBio: 'تأسست شركة هرمود للاتصالات الصومالية في عام 2002. وسرعان ما أصبحت رائدة في السوق، حيث قدمت خدمات الهاتف المحمول GSM، ومنتجها الأكثر تأثيراً، EVC Plus، الذي حول الصومال إلى مجتمع غير نقدي إلى حد كبير.',
        timeline: [
            { year: '2002', title: 'التأسيس', description: 'تأسست من قبل مجموعة من المساهمين في مقديشو.' },
            { year: '2011', title: 'EVC Plus', description: 'إطلاق خدمة الأموال عبر الهاتف المحمول EVC Plus.' },
            { year: '2013', title: '4G LTE', description: 'الأولى التي تقدم خدمات 4G في المنطقة.' }
        ],
        archives: [],
        news: []
      }
    }
  },
  {
      id: '5',
      category: Category.POLITICS,
      verified: true,
      verificationLevel: VerificationLevel.GOLDEN,
      imageUrl: 'https://picsum.photos/204/204?grayscale',
      influence: { support: 95, neutral: 4, opposition: 1 },
      isOrganization: false,
      status: 'ACTIVE' as ProfileStatus,
      dateStart: '1937',
      content: {
        en: {
          name: 'Edna Adan Ismail',
          title: 'Healthcare Pioneer',
          location: 'Hargeisa',
          shortBio: 'Founder of the Edna Adan Maternity Hospital and former Foreign Minister.',
          fullBio: 'Edna Adan Ismail is a trailblazer in women\'s health and Somali politics. After a career with the WHO, she returned to sell her assets to build a maternity hospital, drastically reducing maternal mortality rates in the region.',
          timeline: [
              { year: '1937', title: 'Birth', description: 'Born in Hargeisa.' },
              { year: '2002', title: 'Hospital Opening', description: 'Opened the Edna Adan Maternity Hospital.' },
              { year: '2003', title: 'Foreign Minister', description: 'Served as Minister of Foreign Affairs for Somaliland.' }
          ],
          archives: [
            { id: 'e1', type: 'IMAGE' as const, title: 'Hospital Groundbreaking', date: '1999', size: '1.2 MB' }
          ],
          news: []
        },
        so: {
          name: 'Edna Aadan Ismaaciil',
          title: 'Hormuudka Caafimaadka',
          location: 'Hargeysa',
          shortBio: 'Aasaasaha Isbitaalka Hooyada iyo Dhallaanka ee Edna Aadan iyo Wasiirkii hore ee Arrimaha Dibadda.',
          fullBio: 'Edna Aadan Ismaaciil waa hormuud dhanka caafimaadka haweenka iyo siyaasadda. Kadib shaqo ay la soo qabatay WHO, waxay iibisay hantideeda si ay u dhisto isbitaal dhalmo, taasoo si weyn u yareysay dhimashada hooyada.',
          timeline: [
              { year: '1937', title: 'Dhalasho', description: 'Waxay ku dhalatay Hargeysa.' },
              { year: '2002', title: 'Furitaanka Isbitaalka', description: 'Waxay furtay Isbitaalka Edna Aadan.' },
              { year: '2003', title: 'Wasiirka Arrimaha Dibadda', description: 'Waxay noqotay Wasiirka Arrimaha Dibadda ee Somaliland.' }
          ],
          archives: [
            { id: 'e1', type: 'IMAGE' as const, title: 'Dhagax-dhiggii Isbitaalka', date: '1999', size: '1.2 MB' }
          ],
          news: []
        },
        ar: {
          name: 'إدنا عدن إسماعيل',
          title: 'رائدة الرعاية الصحية',
          location: 'هرجيسا',
          shortBio: 'مؤسسة مستشفى إدنا عدن للولادة ووزيرة الخارجية السابقة.',
          fullBio: 'إدنا عدن إسماعيل رائدة في صحة المرأة والسياسة الصومالية. بعد مسيرة مهنية مع منظمة الصحة العالمية، عادت لبيع أصولها لبناء مستشفى للولادة، مما قلل بشكل كبير من معدلات وفيات الأمهات في المنطقة.',
          timeline: [
              { year: '1937', title: 'الميلاد', description: 'ولدت في هرجيسا.' },
              { year: '2002', title: 'افتتاح المستشفى', description: 'افتتحت مستشفى إدنا عدن للولادة.' },
              { year: '2003', title: 'وزيرة الخارجية', description: 'شغلت منصب وزير الخارجية في صوماليلاند.' }
          ],
          archives: [
            { id: 'e1', type: 'IMAGE' as const, title: 'وضع حجر الأساس للمستشفى', date: '1999', size: '1.2 MB' }
          ],
          news: []
        }
      }
  },
  {
      id: '6',
      category: Category.BUSINESS,
      verified: true,
      verificationLevel: VerificationLevel.STANDARD,
      imageUrl: 'https://picsum.photos/206/206?grayscale',
      influence: { support: 60, neutral: 30, opposition: 10 },
      isOrganization: true,
      status: 'ACTIVE' as ProfileStatus,
      dateStart: '2015',
      content: {
        en: {
          name: 'Blue Sky Aviation',
          title: 'Regional Logistics & Travel',
          location: 'Bosaso / Mogadishu',
          shortBio: 'A rising logistics and travel agency providing connecting flights across the Horn of Africa.',
          fullBio: 'Blue Sky Aviation has quickly become a reliable partner for cargo and passenger transport in the East African region. Focusing on affordability and safety, they have connected smaller regional airports to international hubs.',
          timeline: [
              { year: '2015', title: 'Founded', description: 'Started as a cargo charter service.' },
              { year: '2018', title: 'Commercial Flights', description: 'Began passenger services to Nairobi and Djibouti.' }
          ],
          archives: [],
          news: []
        },
        so: {
          name: 'Blue Sky Aviation',
          title: 'Saadka & Safarka Gobolka',
          location: 'Boosaaso / Muqdisho',
          shortBio: 'Shirkad duulimaad iyo saadka oo isku xirta Geeska Afrika.',
          fullBio: 'Blue Sky Aviation waxay noqotay shirkad lagu kalsoonaan karo oo qaabilsan xamuulka iyo rakaabka Geeska Afrika. Iyadoo diiradda saareysa qiimo jaban iyo badbaado, waxay isku xirtay garoomada yaryar iyo kuwa caalamiga ah.',
          timeline: [
              { year: '2015', title: 'Aasaaskii', description: 'Waxay ku bilaabatay adeeg xamuul.' },
              { year: '2018', title: 'Duulimaadyada Ganacsiga', description: 'Waxay bilowday adeegga rakaabka ee Nairobi iyo Jabuuti.' }
          ],
          archives: [],
          news: []
        },
        ar: {
          name: 'طيران السماء الزرقاء',
          title: 'اللوجستيات والسفر الإقليمي',
          location: 'بوصاصو / مقديشو',
          shortBio: 'وكالة لوجستيات وسفر صاعدة توفر رحلات ربط عبر القرن الأفريقي.',
          fullBio: 'أصبحت طيران السماء الزرقاء شريكاً موثوقاً لنقل البضائع والركاب في منطقة شرق أفريقيا. بالتركيز على التكلفة المعقولة والسلامة، قامت بربط المطارات الإقليمية الصغيرة بالمراكز الدولية.',
          timeline: [
              { year: '2015', title: 'التأسيس', description: 'بدأت كخدمة تأجير شحن.' },
              { year: '2018', title: 'الرحلات التجارية', description: 'بدأت خدمات الركاب إلى نيروبي وجيبوتي.' }
          ],
          archives: [],
          news: []
        }
      }
  }
];

export const getProfiles = (lang: Language): Profile[] => {
  return RAW_DATA.map(p => ({
    id: p.id,
    category: p.category,
    categoryLabel: UI_TEXT[lang][CATEGORY_MAP[p.category]] || p.category,
    verified: p.verified,
    verificationLevel: p.verificationLevel,
    imageUrl: p.imageUrl,
    influence: p.influence,
    isOrganization: p.isOrganization,
    status: p.status,
    dateStart: p.dateStart,
    dateEnd: p.dateEnd,
    archives: p.content[lang].archives || [],
    news: p.content[lang].news || [],
    name: p.content[lang].name,
    title: p.content[lang].title,
    location: p.content[lang].location,
    shortBio: p.content[lang].shortBio,
    fullBio: p.content[lang].fullBio,
    timeline: p.content[lang].timeline
  }));
};